# Generated by Django 5.0.3 on 2024-04-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo_app.master')),
                ('statename', models.CharField(max_length=300, verbose_name='State Name')),
            ],
            bases=('demo_app.master',),
        ),
    ]
