# Generated by Django 5.0.3 on 2024-04-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='New_State',
        ),
    ]
