# Generated by Django 5.0.3 on 2024-04-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_rename_state_new_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo_app.master')),
                ('districtname', models.CharField(max_length=200, unique=True)),
                ('state', models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='demo_app.new_state')),
            ],
            bases=('demo_app.master',),
        ),
    ]
