# Generated by Django 5.0.3 on 2024-04-19 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_gender',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo_app.master')),
                ('student_details', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=900)),
            ],
            bases=('demo_app.master',),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.new_state'),
        ),
    ]
