# Generated by Django 5.0.3 on 2024-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_student_gender_alter_district_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_gender',
            name='StudentName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
